#!/usr/bin/env bash
# This script installs and configures HAProxy to distribute traffic between web-01 and web-02

# Update package lists and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # See: https://ssl-config.mozilla.org/#server=haproxy&version=2.0.0
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 100.25.147.212:80 check
    server web02 54.145.156.109:80 check
EOL

# Enable HAProxy to start on boot
sudo service haproxy restart

# Display a message indicating the script has completed successfully
echo "HAProxy installed and configured to distribute traffic between web-01 and web-02 using round-robin algorithm"
