#!/usr/bin/env bash
# currently running process


# Use ps to list all processes, displaying PID, PPID, user, and command
# ps command options:
# -e: Select all processes.
# --forest: Display processes in a hierarchical/tree format
ps -e --forest aux
