#!/usr/bin/env bash
# indefinite looop
echo "$$" > pid
i=0
until [ $i -eq 1 ];
do
echo "To infinity and beyond";
sleep 2;
    if [ -e stop_4_to_infinity.signal ]; then
        echo "Terminated"
        rm stop_4_to_infinity.signal
    fi
done
