#!/usr/bin/env bash
# prints est school 10 times using until loop
# Initialize counter
counter=0

# Loop until counter reaches 10
until [ $counter -ge 10 ]
do
    echo "Best School"
    
    # Increment counter
    ((counter++))
done
