#!/usr/bin/env bash
# 6-superstitious_numbers
# Initialize counter
counter=1

# Loop until counter reaches 20
while [ $counter -le 20 ]
do
    # Display the current number
    echo $counter
    
    # Check for special iterations and display messages accordingly
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    
    # Increment counter
    ((counter++))
done
